import localFont from 'next/font/local'
import './globals.css'

// import { Inter, Roboto_Mono } from 'next/font/google'
import { Inter, Roboto_Mono, Montserrat } from 'next/font/google'

// const inter = Inter({
//   subsets: ['latin'],
//   variable: '--font-inter',
//   display: 'swap',
// })

// const roboto_mono = Roboto_Mono({
//   subsets: ['latin'],
//   variable: '--font-roboto-mono',
//   display: 'swap',
// })

const montserrat = Montserrat({
  // subsets: ['latin'],
  // variable: '--font-montserrat',
  // display: 'swap',
  weight: ['400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-montserrat',
  display: 'swap',
})


const agrandir = localFont({
  src: './fonts/Agrandir-Regular.otf',
  variable: '--font-agrandir',
  display: 'swap',
})

const agrandirWide = localFont({
  src: './fonts/Agrandir-WideLight.otf',
  variable: '--font-agrandir-wide',
  display: 'swap',
})

const agrandirGrandLight = localFont({
  src: './fonts/Agrandir-GrandLight.otf',
  variable: '--font-agrandir-grand-light',
  display: 'swap',
})

const agrandirGrandHeavy = localFont({
  src: './fonts/Agrandir-GrandHeavy.otf',
  variable: '--font-agrandir-grand-bold',
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${montserrat.variable} ${agrandir.variable} ${agrandirWide.variable} ${agrandirGrandLight.variable} ${agrandirGrandHeavy.variable}`}>
      <body>{children}</body>
    </html>
  )
}


 